### ISSUE TITLE
Start Menu

### ISSUE THREAD

**Issue by kwwham** [UCSB-CS56-Projects/cs56-games-Go#11]
Implement a menu that once the game is run it prompts the user to pick a different size board and subsequently creates the board accordingly.

A lot of the code is based on the 19x19 board. So completing this issue would include a bit of re-factoring to make the board re-sizeable.

Typical board sizes include 5x5, 9x9, 13x13, and 19x19

~estimated 300

**Comment by asyung** [comment]
F16 OK (300 points)

**Comment by johnnyzhang1738** [comment]
F17 OK (300 points)
