### ISSUE TITLE
Clean up repo and refactor into new project structure

### ISSUE THREAD

**Issue by kjorg50** [UCSB-CS56-Projects/cs56-games-Go#12]
There are some leftover artifacts from old CS56 projects. Here's what needs to be done
- remove the `jws/` folder
- remove `numbererdsource.txt`
- add the new package stucture to the code
  - see [step 2 here](https://foo.cs.ucsb.edu/56wiki/index.php/W14:Projects:proj1)
- [update the build.xml file](https://foo.cs.ucsb.edu/56wiki/index.php/MantisMigration:build.xml_modifications)

Ideally, this should be done _before_ completing #5, #7, #8, #10, #11 

~estimated 50

**Comment by asyung** [comment]
F16 OK (50 points)

**Comment by johnnyzhang1738** [comment]
50 points OK
