### ISSUE TITLE
Resolution problem.

### ISSUE THREAD

**Issue by nickabrahan** [ucsb-cs56-projects/cs56-games-Go#13]
The game doesn't automatically adjust to the resolution of the screen that it's being played on. On screens with a resolution 1920x1080 or larger, the program has no problem fitting onto the screen, but when it comes to the displays (such as the one in Phelps 3525) that have less resolution, the game opens and is cut off by the limits of the screen.

~estimated 200;

**Comment by asyung** [comment]
F16 OK (200 points)
