### ISSUE TITLE
i think it's a glitch but i'm not sure

### ISSUE THREAD

**Issue by liujeffreyk** [UCSB-CS56-Projects/cs56-games-Go#20]
x's turn
##o##
#oxo#
ox#xo
#oxo#
##o##

Suppose it is x's turn. x tries to put stone in the center of the diamond. Of course, this is illegal because that would result in a suicide. The program recognizes this and does not let x place a stone there. x must place a stone somewhere else. After x places the stone somewhere else, something interesting happens. The suicide mysteriously happens. And the picture looks like this.

o's turn
##o###x
#o#o###
o###o##
#o#o###
##o####

I don't fully understand the rules of Go, but I'm pretty sure that was not supposed to happen. x should not be allowed to make his own stones disappear on his turn.

**Comment by liujeffreyk** [comment]
pictures didn't come out right.

x's turn
~~o~~
~oxo~
ox~xo
~oxo~
~~o~~

o's turn
~~o~~~x
~o~o~~~
o~~~o~~
~o~o~~~
~~o~~~~

**Comment by liujeffreyk** [comment]
pictures didn't come out right.

x's turn
o
~oxo~
ox~xo
~oxo~
o

o's turn
o~x
~o~o~~~
o~o
~o~o~~~
o~~

**Comment by liujeffreyk** [comment]
x's turn
##o##
#oxo#
ox#xo
#oxo#
##o##

Suppose it is x's turn. x tries to put stone in the center of the diamond. First click results in illegal move message. Suppose x double clicks in the center.

o's turn
##o##
#o#o#
o#x#o
#o#o#
##o##

**Comment by omeedrabani** [comment]
Approved: 100 pts
