### ISSUE TITLE
README inaccuracy

### ISSUE THREAD

**Issue by liujeffreyk** [UCSB-CS56-Projects/cs56-games-Go#23]
"Go.java -- The main hub that controls all the pieces."

The above is probably incorrect. I think Go.java is the outdated (containing main) version of the game that does not use graphics and is played entirely on the terminal. It is not used at all and could probably be deleted.

GoGui1.java is the updated (containing main) version with all the cool graphics...though the graphics could be made even cooler.

**Comment by omeedrabani** [comment]
Approved: 25 pts
