### ISSUE TITLE
Repeated Code

### ISSUE THREAD

**Issue by laurendumapias** [UCSB-CS56-Projects/cs56-games-Go#26]
There is a lot of code that is repetitive, so we need to clean up the code to stop being "DRY".

**Comment by omeedrabani** [comment]
W16 OK

**Comment by xiaoheh** [comment]
Estimate: 100 pts

**Comment by asyung** [comment]
F16 OK (100 points)

**Comment by johnnyzhang1738** [comment]
OK (50 points)
