### ISSUE TITLE
Another glitch

### ISSUE THREAD

**Issue by liujeffreyk** [UCSB-CS56-Projects/cs56-games-Go#27]
o to move
#oo#
#xxo
oxx#
#o##

x to move
#oo#
o##o
o###
#o##

What should have happened
x to move
#oo#
oxxo
oxx#
#o##

Capture algorithm has issues. Original creator made some careless errors.
Estimated points: 100

**Comment by liujeffreyk** [comment]
o to move
o to move
#oo##
#xxo#
oxxxo
#oxx#
##oo#

x to move
#oo##
o##o#
o##xo
#oxx#
##oo#

A variant of the glitch.

**Comment by liujeffreyk** [comment]
Nvm, whoever made the original code made some silly mistakes. Doesn't take much effort to fix.
Points suggested: 100

**Comment by omeedrabani** [comment]
Approved: 100 pts
