### ISSUE TITLE
Implement KO rule 

### ISSUE THREAD

**Issue by laurendumapias** [UCSB-CS56-Projects/cs56-games-Go#28]
This is an important rule to GO! The rule goes as follows: "Consequence (ko rule). One may not play in such a way as to recreate the board position following one's previous move". (Source: https://en.wikipedia.org/wiki/Rules_of_go)

~estimated points 200

**Comment by omeedrabani** [comment]
W16 OK

**Comment by asyung** [comment]
F16 OK (200 points)
