### ISSUE TITLE
Surrender vs End Game 

### ISSUE THREAD

**Issue by laurendumapias** [UCSB-CS56-Projects/cs56-games-Go#29]
Right now, the surrender button just ends the game and determine the winner based on the number of stones. Semantically, surrender means that a person gives up the win to the other player. The player who clicks the surrender button should lose and when the two players want to end the game, they should click the end game button instead.

~estimated 100 points

**Comment by omeedrabani** [comment]
W16 OK

**Comment by asyung** [comment]
F16 OK (100 points)

**Comment by dong1016** [comment]
Can this be separated into just fixing surrender button, end game button is completely unrelated and the way they did it with the surrender code makes no sense code wise and game logic wise.
