### ISSUE TITLE
Score "Terminal" issue

### ISSUE THREAD

**Issue by chunqingliu** [UCSB-CS56-Projects/cs56-games-Go#37]
The score "terminal" is a giant white box and it has completely different color feature from the game window. Also, the score window is too big and we could see that more than half of the space will never be used.
 
-Adding new colors to the score window and change the size of the score window to be suitable for the user.

Estimated points: 150 points

**Comment by xiaoheh** [comment]
Approved: 100 pts

**Comment by RityZhang** [comment]
done
