### ISSUE TITLE
Cleaning the previous "messy" code

### ISSUE THREAD

**Issue by chunqingliu** [UCSB-CS56-Projects/cs56-games-Go#42]
There are lots of code that is not useful anymore and some codes are not necessary and helpful for the game. Thus, cleaning up some code will bring us lots of convenience.

Estimate :100 points

**Comment by xiaoheh** [comment]
Approved

**Comment by xiaoheh** [comment]
M16 OK

**Comment by asyung** [comment]
F16 OK (100 points)

**Comment by johnnyzhang1738** [comment]
F17 OK (50 points)
