### ISSUE TITLE
Bug - Stones doesn't show color on mac

### ISSUE THREAD

**Issue by zhanchengqian** [UCSB-CS56-Projects/cs56-games-Go#47]
When using mac to run the software, the Stones doesn't show color. 
Picture attached, might be something with the coding itself. 
Working perfectly on Linux and Windows machines. 
200 points 
![screen shot 2016-09-29 at 5 29 09 pm](https://cloud.githubusercontent.com/assets/20016679/18977033/d80d6440-866b-11e6-90a7-6e57de3a4b8b.png)

**Comment by asyung** [comment]
F16 OK (200 points)
