### ISSUE TITLE
Fix GamePlay Bug

### ISSUE THREAD

**Issue by jstaahl** [UCSB-CS56-Projects/cs56-games-Go#5]
As of right now, the game does not allow a user to ever place a piece inside of a space where they would have no liberties. This sounds correct, but actually, in the game Go, a user is allowed to place a piece in a space with no liberties if it will result in capturing some of the opponents pieces and after the removal of these pieces the placed piece has liberties (and as long as it does not violate the Ko rule).
Example:
```
+  +  +  +  +  +  +
+  +  B  +  +  +  +
+  B  +  B  +  +  +
+  +  B  +  +  +  +
+  +  +  +  +  +  +
```
A white piece could not be placed in the center of these 4 black pieces because it would have no liberties.

However, in the following configuration:
```
+  +  +  +  +  +  +
+  +  B  W  W  +  +
+  B  +  B  B  W  +
+  +  B  W  W  +  +
+  +  +  +  +  +  +
```
A white piece would be allowed to be placed in the middle of the black pieces because when placed there, white would surround and capture two of the black pieces resulting in:
```
+  +  +  +  +  +  +
+  +  B  W  W  +  +
+  B  W  +  +  W  +
+  +  B  W  W  +  +
+  +  +  +  +  +  +
```

Fix this gameplay bug, and also make sure the Ko rule is implemented.
(Search Go Ko rule)

In addition, become familiar with all of the rules and corner cases of Go and make sure these are all well implemented as well.

~estimated 200

**Comment by laurendumapias** [comment]
Please reconsider the points allocated for this task. :) It took much longer than 200 points worth.

**Comment by omeedrabani** [comment]
Approved: 300 pts
