### ISSUE TITLE
Implement either Area Scoring or Territory Scoring

### ISSUE THREAD

**Issue by jstaahl** [UCSB-CS56-Projects/cs56-games-Go#7]
It appears as though the scores of the two players is solely determined by the number of pieces they each have on the board as seen in getWinner() in GoGrid.java.

Fix this scoring system to use either Area Scoring or Territory scoring, both of which also take into account for a player the number of empty points only their stones surround.

Make sure the type of scoring used is consistent with the type of scoring discussed in the Directions Pop up.

~estimated 150

**Comment by laurendumapias** [comment]
We think this will be difficult and should be worth ~estimated 500

**Comment by omeedrabani** [comment]
W16 OK

**Comment by asyung** [comment]
F16 OK (400 points)
