### ISSUE TITLE
Fix Surrender

### ISSUE THREAD

**Issue by brianhumphreys** [ucsb-cs56-projects/cs56-games-Go#74]
make the surrender button end the game and find a winner based on points.

**Comment by johnnyzhang1738** [comment]
f17 ok 100 points

**Comment by brianslee** [comment]
W18 Ok 100 Points

**Comment by praxideus** [comment]
If one player is in the lead and they press the surrender button, the game would end and the player who pressed the surrender button would win, according to the description for this issue.

I suggest that the surrender button, when implemented, would result in the other player winning automatically. The player who pressed the surrender button would lose, as if they are surrendering.

**Comment by brianslee** [comment]
Completed. Closed W18
