### ISSUE TITLE
No option to restart a game.

### ISSUE THREAD

**Issue by nickabrahan** [UCSB-CS56-Projects/cs56-games-Go#8]
Once a game is finished, either by filling up the board or one player surrendering, the program doesn't give an option of making a new game. The only way to play again is essentially to restart the program.

Ideally, there would be an option that would pop out once the game is finished to start a new game, clearing the board and starting the game from scratch.

Having a scoreboard for games won could also be implemented, and would be nice for those people who are really addicted to Go.

estimated ~70

**Comment by laurendumapias** [comment]
Please reconsider the points allocated for this issue. ~estimated is 200

**Comment by omeedrabani** [comment]
Approved: 200 pts
